# Generated by Django 2.2.4 on 2019-08-26 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


DEFAULT_GOOD_TYPES = [
    {'name': 'Coffee', 'description': 'Hot coffee for your soul.'}
]


def add_default_goodtypes(apps, schema_editor):
    GoodType = apps.get_model('coffeeBot', 'GoodType')

    GoodType.objects.bulk_create(
        [GoodType(**goodtype) for goodtype in DEFAULT_GOOD_TYPES]
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodType',
            fields=[
                ('goodtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'good_types',
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('volume_id', models.AutoField(primary_key=True, serialize=False)),
                ('volume', models.CharField(max_length=8)),
                ('unit_of_measure', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'volumes',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('good_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('goodtype', models.ForeignKey(db_column='goodtype', on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='coffeeBot.GoodType')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodVolume',
            fields=[
                ('goodvolume_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('good', models.ForeignKey(db_column='good', on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='coffeeBot.GoodVolume')),
                ('volume', models.ForeignKey(db_column='volume', on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='coffeeBot.Volume')),
            ],
            options={
                'db_table': 'good_volume_links',
                'unique_together': {('good', 'volume')},
            },
        ),
        migrations.RunPython(
            add_default_goodtypes,
        ),
    ]
